name: CI 

on:
  push:
    branches: [main, dtp/vite-build-changes]
  pull_request:
    branches: [main, dtp/vite-build-changes]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15.0]
        browser: ["chrome"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # Run vitest tests
      - run: npm run test
        env:
          CI: true
      # Build code and run as a prod server in the bg
      - run: npm run build 
      - run: npm run start-prod &
      # Run nightwatch tests
      - run: npm run test:e2e
        env:
          CI: true
